### ISSUE TITLE
Button 구현 : NodeList에 addEventListener 접근

### ISSUE THREAD

**Issue by 4BFC** [4BFC/Js#2]
* Error Message :
Uncaught (in promise) TypeError: btn_group.addEventListener is not a function
    at btn_data (menu_btn.js:24:13)
    at menu_btn.js:34:13

NodeList는 DOM 요소들의 컬렉션을 나타낸다. 여러 개의 요소를 포함할 수 있기에 addEventListener를 직접 NodeList에 적용할 수 없다.

**Comment by 4BFC** [comment]
foreach를 사용해서 addEventlistener 구현
